ups:
  - name: ups1
    host: 192.168.1.10
    port: 3551
    interval_seconds: 30
    alert_loadpct_high: 80
    alert_bcharge_low: 40
    alert_on_battery: true
    alert_runtime_low_minutes: 10

smtp:
  host: 192.168.1.50
  port: 25
  username: ""
  password: ""  # or set env SMTP_PASSWORD
  use_tls: false
  use_ssl: false
  from_addr: ups-monitor@example.local
  to_addrs:
    - admin@example.local
  subject_prefix: "[UPS]"
